/* 작업용 DB 사용자(유저) 생성
유저명 : mystudy
암호 : mystudypw
*/
-- USER SQL
CREATE USER MYSTUDY IDENTIFIED BY "mystudypw"  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "MYSTUDY" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "MYSTUDY" ;
GRANT "RESOURCE" TO "MYSTUDY" ;

-- SYSTEM PRIVILEGES
